[workspace]
members = [
    "programs/vote_program",
    "programs/verifier_program",
]
resolver = "2"

[patch.crates-io]
# Use older blake3 version that doesn't require constant_time_eq 0.4.2
blake3 = { git = "https://github.com/BLAKE3-team/BLAKE3.git", tag = "1.5.0" }
